// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/DraconDev/go-templ-htmx-ex/templates/layouts"

func Pricing(userInfo layouts.UserInfo) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if userInfo.LoggedIn {
			templ_7745c5c3_Err = layouts.Layout("Pricing | Startup Platform", "Choose the plan that fits your needs", layouts.NavigationLoggedIn(userInfo), PricingContent(userInfo)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = layouts.Layout("Pricing | Startup Platform", "Choose the plan that fits your needs", layouts.NavigationLoggedOut(), PricingContent(userInfo)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

func PricingContent(userInfo layouts.UserInfo) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16\"><div class=\"text-center mb-16\"><h1 class=\"text-4xl font-bold text-white mb-4\">Simple, transparent pricing</h1><p class=\"text-xl text-gray-400\">Choose the plan that's right for your business.</p></div><div class=\"grid grid-cols-1 md:grid-cols-3 gap-8\"><!-- Free Plan --><div class=\"glass-card rounded-2xl p-8 relative overflow-hidden\"><h3 class=\"text-xl font-semibold text-white mb-2\">Starter</h3><div class=\"flex items-baseline mb-6\"><span class=\"text-4xl font-bold text-white\">$0</span> <span class=\"text-gray-400 ml-2\">/month</span></div><p class=\"text-gray-400 mb-6\">Perfect for trying out the platform and personal projects.</p><ul class=\"space-y-4 mb-8\"><li class=\"flex items-center text-gray-300\"><i class=\"fas fa-check text-green-400 mr-3\"></i> 3 Projects</li><li class=\"flex items-center text-gray-300\"><i class=\"fas fa-check text-green-400 mr-3\"></i> Basic Analytics</li><li class=\"flex items-center text-gray-300\"><i class=\"fas fa-check text-green-400 mr-3\"></i> Community Support</li></ul>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if userInfo.LoggedIn {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<button class=\"w-full py-3 px-4 rounded-lg bg-gray-700 text-white font-medium cursor-not-allowed opacity-50\">Current Plan</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<a href=\"/login\" class=\"block w-full py-3 px-4 rounded-lg bg-white text-black font-bold text-center hover:bg-gray-200 transition-colors\">Get Started</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div><!-- Pro Plan --><div class=\"glass-card rounded-2xl p-8 relative overflow-hidden border-cyan-500/50 border-2 transform scale-105 z-10\"><div class=\"absolute top-0 right-0 bg-cyan-500 text-white text-xs font-bold px-3 py-1 rounded-bl-lg\">POPULAR</div><h3 class=\"text-xl font-semibold text-white mb-2\">Pro</h3><div class=\"flex items-baseline mb-6\"><span class=\"text-4xl font-bold text-white\">$29</span> <span class=\"text-gray-400 ml-2\">/month</span></div><p class=\"text-gray-400 mb-6\">For growing businesses and serious developers.</p><ul class=\"space-y-4 mb-8\"><li class=\"flex items-center text-gray-300\"><i class=\"fas fa-check text-cyan-400 mr-3\"></i> Unlimited Projects</li><li class=\"flex items-center text-gray-300\"><i class=\"fas fa-check text-cyan-400 mr-3\"></i> Advanced Analytics</li><li class=\"flex items-center text-gray-300\"><i class=\"fas fa-check text-cyan-400 mr-3\"></i> Priority Support</li><li class=\"flex items-center text-gray-300\"><i class=\"fas fa-check text-cyan-400 mr-3\"></i> API Access</li></ul>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if userInfo.LoggedIn {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<button hx-post=\"/api/payment/checkout\" hx-vals='{\"price_id\": \"price_1QhEBSFhH6dwUiIHSUnHP957\", \"product_id\": \"prod_RZaVDAN6Uf4Qfb\"}' hx-headers='{\"Content-Type\": \"application/json\"}' hx-ext=\"json-enc\" class=\"w-full py-3 px-4 rounded-lg bg-gradient-to-r from-cyan-500 to-blue-600 text-white font-bold hover:from-cyan-400 hover:to-blue-500 transition-all shadow-lg shadow-cyan-500/20\">Upgrade to Pro</button><div id=\"checkout-error\" class=\"text-red-400 text-sm mt-2 text-center hidden\"></div><script>\n\t\t\t\t\t\tdocument.body.addEventListener('htmx:afterRequest', function(evt) {\n\t\t\t\t\t\t\tif (evt.detail.successful) {\n\t\t\t\t\t\t\t\tconst resp = JSON.parse(evt.detail.xhr.response);\n\t\t\t\t\t\t\t\tif (resp.checkout_url) {\n\t\t\t\t\t\t\t\t\twindow.location.href = resp.checkout_url;\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t} else {\n\t\t\t\t\t\t\t\tconst errorDiv = document.getElementById('checkout-error');\n\t\t\t\t\t\t\t\terrorDiv.textContent = \"Checkout failed. Please try again.\";\n\t\t\t\t\t\t\t\terrorDiv.classList.remove('hidden');\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t});\n\t\t\t\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<a href=\"/login\" class=\"block w-full py-3 px-4 rounded-lg bg-gradient-to-r from-cyan-500 to-blue-600 text-white font-bold text-center hover:from-cyan-400 hover:to-blue-500 transition-all shadow-lg shadow-cyan-500/20\">Get Started</a>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><!-- Enterprise Plan --><div class=\"glass-card rounded-2xl p-8 relative overflow-hidden\"><h3 class=\"text-xl font-semibold text-white mb-2\">Enterprise</h3><div class=\"flex items-baseline mb-6\"><span class=\"text-4xl font-bold text-white\">Custom</span></div><p class=\"text-gray-400 mb-6\">For large organizations with specific requirements.</p><ul class=\"space-y-4 mb-8\"><li class=\"flex items-center text-gray-300\"><i class=\"fas fa-check text-purple-400 mr-3\"></i> Everything in Pro</li><li class=\"flex items-center text-gray-300\"><i class=\"fas fa-check text-purple-400 mr-3\"></i> Dedicated Support</li><li class=\"flex items-center text-gray-300\"><i class=\"fas fa-check text-purple-400 mr-3\"></i> SLA</li><li class=\"flex items-center text-gray-300\"><i class=\"fas fa-check text-purple-400 mr-3\"></i> Custom Integrations</li></ul><a href=\"mailto:sales@example.com\" class=\"block w-full py-3 px-4 rounded-lg bg-white/10 text-white font-medium text-center hover:bg-white/20 transition-colors\">Contact Sales</a></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
