// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID      `json:"id"`
	AuthID    string         `json:"auth_id"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	Picture   sql.NullString `json:"picture"`
	IsAdmin   sql.NullBool   `json:"is_admin"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type UserPreference struct {
	ID                 uuid.UUID      `json:"id"`
	UserID             uuid.NullUUID  `json:"user_id"`
	Theme              sql.NullString `json:"theme"`
	Language           sql.NullString `json:"language"`
	EmailNotifications sql.NullBool   `json:"email_notifications"`
	PushNotifications  sql.NullBool   `json:"push_notifications"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	Timezone           sql.NullString `json:"timezone"`
	EmailBilling       sql.NullBool   `json:"email_billing"`
}
