// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUserPreferences = `-- name: CreateUserPreferences :one
INSERT INTO user_preferences (
    user_id, theme, language, timezone, email_notifications, email_billing, push_notifications
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, theme, language, email_notifications, push_notifications, created_at, updated_at, timezone, email_billing
`

type CreateUserPreferencesParams struct {
	UserID             uuid.NullUUID  `json:"user_id"`
	Theme              sql.NullString `json:"theme"`
	Language           sql.NullString `json:"language"`
	Timezone           sql.NullString `json:"timezone"`
	EmailNotifications sql.NullBool   `json:"email_notifications"`
	EmailBilling       sql.NullBool   `json:"email_billing"`
	PushNotifications  sql.NullBool   `json:"push_notifications"`
}

func (q *Queries) CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) (UserPreference, error) {
	row := q.queryRow(ctx, q.createUserPreferencesStmt, createUserPreferences,
		arg.UserID,
		arg.Theme,
		arg.Language,
		arg.Timezone,
		arg.EmailNotifications,
		arg.EmailBilling,
		arg.PushNotifications,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.EmailNotifications,
		&i.PushNotifications,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.EmailBilling,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT id, user_id, theme, language, email_notifications, push_notifications, created_at, updated_at, timezone, email_billing FROM user_preferences
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID uuid.NullUUID) (UserPreference, error) {
	row := q.queryRow(ctx, q.getUserPreferencesStmt, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.EmailNotifications,
		&i.PushNotifications,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.EmailBilling,
	)
	return i, err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE user_preferences
SET 
    theme = COALESCE($2, theme),
    language = COALESCE($3, language),
    timezone = COALESCE($4, timezone),
    email_notifications = COALESCE($5, email_notifications),
    email_billing = COALESCE($6, email_billing),
    push_notifications = COALESCE($7, push_notifications),
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, theme, language, email_notifications, push_notifications, created_at, updated_at, timezone, email_billing
`

type UpdateUserPreferencesParams struct {
	UserID             uuid.NullUUID  `json:"user_id"`
	Theme              sql.NullString `json:"theme"`
	Language           sql.NullString `json:"language"`
	Timezone           sql.NullString `json:"timezone"`
	EmailNotifications sql.NullBool   `json:"email_notifications"`
	EmailBilling       sql.NullBool   `json:"email_billing"`
	PushNotifications  sql.NullBool   `json:"push_notifications"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error) {
	row := q.queryRow(ctx, q.updateUserPreferencesStmt, updateUserPreferences,
		arg.UserID,
		arg.Theme,
		arg.Language,
		arg.Timezone,
		arg.EmailNotifications,
		arg.EmailBilling,
		arg.PushNotifications,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.EmailNotifications,
		&i.PushNotifications,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.EmailBilling,
	)
	return i, err
}
