// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countUsersStmt, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersCreatedThisWeek = `-- name: CountUsersCreatedThisWeek :one
SELECT COUNT(*) FROM users
WHERE created_at > NOW() - INTERVAL '1 week'
`

func (q *Queries) CountUsersCreatedThisWeek(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countUsersCreatedThisWeekStmt, countUsersCreatedThisWeek)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersCreatedToday = `-- name: CountUsersCreatedToday :one
SELECT COUNT(*) FROM users WHERE DATE(created_at) = CURRENT_DATE
`

func (q *Queries) CountUsersCreatedToday(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countUsersCreatedTodayStmt, countUsersCreatedToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (auth_id, email, name, picture, is_admin)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, auth_id, email, name, picture, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	AuthID  string         `json:"auth_id"`
	Email   string         `json:"email"`
	Name    string         `json:"name"`
	Picture sql.NullString `json:"picture"`
	IsAdmin sql.NullBool   `json:"is_admin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.AuthID,
		arg.Email,
		arg.Name,
		arg.Picture,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminUsers = `-- name: GetAdminUsers :many
SELECT id, auth_id, email, name, picture, is_admin, created_at, updated_at FROM users WHERE is_admin = true ORDER BY created_at DESC
`

func (q *Queries) GetAdminUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.getAdminUsersStmt, getAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AuthID,
			&i.Email,
			&i.Name,
			&i.Picture,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, auth_id, email, name, picture, is_admin, created_at, updated_at FROM users ORDER BY created_at DESC
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.query(ctx, q.getAllUsersStmt, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AuthID,
			&i.Email,
			&i.Name,
			&i.Picture,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentUsers = `-- name: GetRecentUsers :many
SELECT id, email, name, created_at FROM users ORDER BY created_at DESC LIMIT 10
`

type GetRecentUsersRow struct {
	ID        uuid.UUID    `json:"id"`
	Email     string       `json:"email"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) GetRecentUsers(ctx context.Context) ([]GetRecentUsersRow, error) {
	rows, err := q.query(ctx, q.getRecentUsersStmt, getRecentUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentUsersRow
	for rows.Next() {
		var i GetRecentUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByAuthID = `-- name: GetUserByAuthID :one
SELECT id, auth_id, email, name, picture, is_admin, created_at, updated_at FROM users WHERE auth_id = $1
`

func (q *Queries) GetUserByAuthID(ctx context.Context, authID string) (User, error) {
	row := q.queryRow(ctx, q.getUserByAuthIDStmt, getUserByAuthID, authID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, auth_id, email, name, picture, is_admin, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, auth_id, email, name, picture, is_admin, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = COALESCE($2, name),
    picture = COALESCE($3, picture),
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserParams struct {
	ID      uuid.UUID      `json:"id"`
	Name    string         `json:"name"`
	Picture sql.NullString `json:"picture"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.exec(ctx, q.updateUserStmt, updateUser, arg.ID, arg.Name, arg.Picture)
	return err
}

const updateUserAdminStatus = `-- name: UpdateUserAdminStatus :exec
UPDATE users SET is_admin = $2 WHERE email = $1
`

type UpdateUserAdminStatusParams struct {
	Email   string       `json:"email"`
	IsAdmin sql.NullBool `json:"is_admin"`
}

func (q *Queries) UpdateUserAdminStatus(ctx context.Context, arg UpdateUserAdminStatusParams) error {
	_, err := q.exec(ctx, q.updateUserAdminStatusStmt, updateUserAdminStatus, arg.Email, arg.IsAdmin)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    auth_id, email, name, picture, is_admin
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (auth_id) DO UPDATE
SET
    email = EXCLUDED.email,
    name = EXCLUDED.name,
    picture = EXCLUDED.picture,
    updated_at = NOW()
RETURNING id, auth_id, email, name, picture, is_admin, created_at, updated_at
`

type UpsertUserParams struct {
	AuthID  string         `json:"auth_id"`
	Email   string         `json:"email"`
	Name    string         `json:"name"`
	Picture sql.NullString `json:"picture"`
	IsAdmin sql.NullBool   `json:"is_admin"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.queryRow(ctx, q.upsertUserStmt, upsertUser,
		arg.AuthID,
		arg.Email,
		arg.Name,
		arg.Picture,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthID,
		&i.Email,
		&i.Name,
		&i.Picture,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
